"""Generators to cycle through docmodels, and get data based on specific filters and/or properties"""


import pickle
from typing import Callable, Optional, Iterable

from mempy4.config import DOCMODEL_PATHS_LIST


def generate_docmodels_from_paths(path_list: Iterable, vocal: bool = True, filter_fct: Optional[Callable] = None):
    """Base generator, yields DocModels based on a list of pickled docmodels paths.

    Args:
        path_list: A list of pickled DocModel paths, can be generated by calling os.listdir on docmodels_path
        vocal: Whether to to print each time 5k docmodels are generated
        filter_fct: None or a function taking a docmodel as argument and returning a bool. Only docmodels for which the function returns true will be yielded.

    Returns:

    """

    i = 0
    for path in path_list:
        with open(path, 'rb') as f:
            try:
                dm = pickle.load(f)
                if (filter_fct is None) or filter_fct(dm):
                    i += 1
                    if vocal and i % 5000 == 0:
                        print(f'Generated {i} docmodels')
                    yield dm
            except EOFError:
                print(f'ERROR! Could not open docmodel at: {path}')


def generate_ids_lemmas(path_list, function_name: str, flatten: bool = True, dms_filter_fct: Optional[Callable] = None, tags_filter_fct: Optional[Callable] = None):
    """Builds on generate_docmodels_from_paths, yields pairs of doc_ids and lemma lists

    For each DocModel, yields the doc id (str) and a list of lemmas (str). The specified function should return a list
    of tags with a 'lemma' attribute. If flatten, paragraphs will be merged. Else, each paragraph will be yielded
    individually, and word_list number will be appended to doc id: '{doc id}_{word_list num}'



    Args:
        path_list: List of pickled docmodel paths, see generate_docmodels_from_paths
        function_name: Name of the docmodel method to call, as a string, e.g. 'get_text_tags' or 'get_text_tags'
        flatten: Whether to flatten the paragraphs. Will affect yield type (1d or 2d list)
        dms_filter_fct: Filter function to pass generate_docmodels_from_paths to filter docmodels
        tags_filter_fct: Filter function taking a Tag object as param and returning a bool. Only lemmas whose tag returns True will be included.

    Returns:

    """

    for dm in generate_docmodels_from_paths(path_list, filter_fct=dms_filter_fct):
        if flatten:
            yield dm.get_id(), [tag.lemma for tag in getattr(dm, function_name)(flatten=flatten)
                                if tags_filter_fct is None or tags_filter_fct(tag)]
        else:
            for i, para in enumerate(getattr(dm, function_name)(flatten=flatten)):
                yield f'{dm.get_id()}_{i}', [tag.lemma for tag in para if tags_filter_fct is None or tags_filter_fct(tag)]


def generate_ids_tags(path_list, function_name, flatten=True):
    for dm in generate_docmodels_from_paths(path_list):
        if flatten:
            yield dm.get_id(), getattr(dm, function_name)(flatten=flatten)
        else:
            for i, para in enumerate(getattr(dm, function_name)(flatten=flatten)):
                yield f'{dm.get_id()}_{i}', para


def generate_all_docmodels():
    """Shortcut to generate all docmodels from DOCMODEL_PATHS_LIST"""

    return generate_docmodels_from_paths(DOCMODEL_PATHS_LIST)


def generate_all_ids_sentences_tags():

    return generate_ids_tags(DOCMODEL_PATHS_LIST, 'get_text_sentences_tags', flatten=False)



